### ISSUE TITLE
Native type handling in expressions (breaks MindtPy)

### ISSUE THREAD

**Issue by alexchandel** [Pyomo/pyomo#2925]
## Summary

I have a `ConcreteModel` with a few indexed Params, Vars, and Constraints that solves fine on Pyomo 6.5.0.  However, upgrading to 6.6.0 causes the `MindtPySolver` to throw a nonsensical exception when I call `solve`.

No other changes at all are made.  Downgrading to Pyomo 6.5.0 and changing nothing else clears the error.  Something in 6.6.0 appears to have caused a regression.

### Steps to reproduce the issue

The full codebase is large and private but I can reproduce the relevant portion.

The solver is constructed and run as:
```py
    def build_solver(neos: bool = False) -> Callable[[ConcreteModel], SolverResults]:
        # irrelevant lines omitted …

        from pyomo.contrib.mindtpy.MindtPy import MindtPySolver  # pylint: disable=import-outside-toplevel
        backend = 'mindtpy'
        solver: MindtPySolver = SolverFactory(backend)
        opt_kwargs = {'mip_solver': 'glpk', 'nlp_solver': 'ipopt', 'tee': True}
        return lambda instance: solver.solve(instance, **opt_kwargs)

def splitter_mass_balance():
    instance = ConcreteModel()

    # initialize Params, Vars, Constraints …

    def splitter_objective_rule(_instance):
        return 1  # fine for now
    instance.Obj_splitter = Objective(rule=splitter_objective_rule, sense=maximize, doc='Objective')
    results = build_solver()(instance)

splitter_mass_balance()  # basically how it's called
```

### Error Message

```python
… (pile of wrappers) …

  File "/Users/alex/proj/proj.py", line 2606, in splitter_mass_balance
    results = build_solver()(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex/proj/proj.py", line 2430, in <lambda>
    return lambda instance: solver.solve(instance, **opt_kwargs)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex/proj/.venv/lib/python3.11/site-packages/pyomo/contrib/mindtpy/MindtPy.py", line 118, in solve
    return SolverFactory(_supported_algorithms[config.strategy][0]).solve(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex/proj/.venv/lib/python3.11/site-packages/pyomo/contrib/mindtpy/algorithm_base_class.py", line 2748, in solve
    self.set_up_solve_data(model, config)
  File "/Users/alex/proj/.venv/lib/python3.11/site-packages/pyomo/contrib/mindtpy/algorithm_base_class.py", line 785, in set_up_solve_data
    if obj.expr.polynomial_degree() == 0:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'polynomial_degree'
```

### Information on your system

Pyomo version: 6.6.0
Python version: 3.11.4
Operating system: macOS 13.4.1
How Pyomo was installed (PyPI, conda, source): PyPI
Solver (if applicable): MindtPy

**Comment by alexchandel** [comment]
Note the objective is trivial, for debugging purposes.  The [Objective](https://pyomo.readthedocs.io/en/stable/pyomo_modeling_components/Objectives.html) documentation does not require the return value of the function to be of type `Expression`, and returning Python constants like `1` works in 6.5.0.

**Comment by alexchandel** [comment]
Does Pyomo 6.6.0 now require us to import `NumericConstant` and wrap constants in that, like this?

```py
    def splitter_objective_rule(_instance):
        return NumericConstant(1)
```

**Comment by bernalde** [comment]
We can write a hack for MindtPy to deal with constant objectives, which seems to be a corner case for using MindtPy as it would represent some feasibility problems. Before we do that, does this reveal some deeper regression within Pyomo? @jsiirola 
In case not, we will prepare a quick fix.

**Comment by alexchandel** [comment]
@bernalde I don't *think* it's MindtPy specific, as that code hasn't changed in many months (since before the release of 6.5.0).  Note that returning a wrapped constant like `NumericConstant(1)` instead of the native value works around the issue.

It seems like Pyomo 6.6.0 no longer permits the return value of the objective function to be a Python native value.  Before, it might've wrapped them in an `Expression` of some kind.

**Comment by ZedongPeng** [comment]
I did a simple test. This results from the change of pyomo core and is not MindtPy specific.

```python
from pyomo.environ import *

m = ConcreteModel()
m.obj = Objective(expr=1)

print(m.obj.expr.polynomial_degree())
```
When running this with Pyomo 6.5.0, the output is `0`.
When running this with Pyomo 6.6.0, the output is 
```
Traceback (most recent call last):
  File "from pyomo.py", line 32, in <module>
    print(m.obj.expr.polynomial_degree())
AttributeError: 'int' object has no attribute 'polynomial_degree'
```

**Comment by alexchandel** [comment]
As I suspected.  I suspect this new restriction was unintentional, but either way, can we document the correct behavior on [Objectives](https://pyomo.readthedocs.io/en/stable/pyomo_modeling_components/Objectives.html) and add a regression test?

**Comment by blnicho** [comment]
We discussed this during the Pyomo dev meeting today and are going to fix this in Pyomo core. The `expr` property will always return a Pyomo type.

**Comment by alexchandel** [comment]
Does that mean that objective functions that simply return a native constant will be lifted to Pyomo expressions returning a Pyomo constant value?
