### PR TITLE
Mindtpy APPSI support

### PR DESCRIPTION
**Pull request by ZedongPeng**
## Summary/Motivation:
This PR adds the support for `appsi_cplex` and `appsi_gurobi` in MindtPy.

**Note**: In this implementation, `appsi_cplex` and `appsi_gurobi` only support multi-tree strategy and don't support `calculate_dual` and `solution_pool`.

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

File: pyomo/contrib/mindtpy/config_options.py [hunk 1]
```diff
@@ -523,7 +523,7 @@ def check_config(config):
         if config.mip_solver not in {'cplex_persistent', 'gurobi_persistent'}:
             config.mip_solver = 'cplex_persistent'
             config.logger.info(
-                'Only cplex_persistent and gurobi_persistent are supported for LP/NLP based Branch and Bound method. The MIP solver has been changed to cplex_persistent.')
+                'Only cplex_persistent, gurobi_persistent are supported for LP/NLP based Branch and Bound method. The MIP solver has been changed to cplex_persistent.')
```
Comment (bernalde) [inline pyomo/contrib/mindtpy/config_options.py:526]: What if the user does not have CPLEX installed? Is this a safe choice to fallback to use CPLEX? I'm inclining more for MindtPy to stop right there and tell the user that either cplex or gurobi persisted need to be used.

File: pyomo/contrib/mindtpy/config_options.py [hunk 2]
```diff
@@ -575,4 +575,23 @@ def check_config(config):
                 'The threads parameter is corrected to 1 since incumbent callback conflicts with multi-threads mode.')
     if config.solution_pool:
         if config.mip_solver not in {'cplex_persistent', 'gurobi_persistent'}:
+            if config.mip_solver in {'appsi_cplex', 'appsi_gurobi'}:
+                config.logger.info("Solution pool does not support APPSI solver yet.")
```
Comment (bernalde) [inline pyomo/contrib/mindtpy/config_options.py:579]: Consider removing yet, as it looks like a promise which I do not know if we want to hold.

File: pyomo/contrib/mindtpy/config_options.py [hunk 3]
```diff
@@ -575,4 +575,23 @@ def check_config(config):
...
             config.mip_solver = 'cplex_persistent'
+    if config.calculate_dual:
```
Comment (bernalde) [inline pyomo/contrib/mindtpy/config_options.py:581]: I have some issues with this option's name, as duals are not exactly what we are computing out of the MIP problems, they are the duals of the continuous relaxation fixed at the optimal values of the integer variables (which is slightly different)...

File: pyomo/contrib/mindtpy/initialization.py [hunk 4]
```diff
@@ -226,17 +226,27 @@ def init_max_binaries(solve_data, config):
     if isinstance(mipopt, PersistentSolver):
         mipopt.set_instance(m)
     mip_args = dict(config.mip_solver_args)
+    # if config.mip_solver in {'appsi_cplex', 'appsi_gurobi'}:
```
Comment (bernalde) [inline pyomo/contrib/mindtpy/initialization.py:229]: Is this comment still relevant?

File: pyomo/contrib/mindtpy/tests/test_mindtpy.py [hunk 5]
```diff
@@ -206,6 +206,23 @@ def test_OA_quadratic_strategy(self):
...
+    @unittest.skipUnless(SolverFactory('appsi_cplex').available(), 
+                         "APPSI_CPLEX not available.")
+    def test_OA_APPSI_solver(self):
+        """Test the outer approximation decomposition algorithm."""
+        with SolverFactory('mindtpy') as opt:
+            for model in model_list:
+                results = opt.solve(model, strategy='OA',
+                                    mip_solver='appsi_cplex',
+                                    nlp_solver=required_solvers[0],
+                                    integer_to_binary=True
```
Comment (bernalde) [inline pyomo/contrib/mindtpy/tests/test_mindtpy.py:219]: This test is checking both APPSI and the integer to binary transformation. Let's check only APPSI here as the following test takes care of the transformation.

File: pyomo/contrib/mindtpy/util.py [hunk 6]
```diff
@@ -499,6 +502,16 @@ def set_solver_options(opt, solve_data, config, solver_type, regularization=Fals
             opt._solver_model.parameters.mip.strategy.presolvenode.set(3)
             if config.add_regularization in {'hess_lag', 'hess_only_lag'}:
                 opt._solver_model.parameters.optimalitytarget.set(3)
+    elif solver_name == 'appsi_cplex':
+        opt.options['timelimit'] = remaining
+        opt.options['mip_tolerances_mipgap'] = config.mip_solver_mipgap
+        # opt.options['load_solution'] = False
```
Comment (bernalde) [inline pyomo/contrib/mindtpy/util.py:508]: Is this comment still relevant?

File: pyomo/contrib/mindtpy/util.py [hunk 7]
```diff
@@ -932,3 +945,13 @@ def get_primal_integral(solve_data, config):
 
     config.logger.info(' {:<25}:   {:>7.4f} '.format('Primal integral', primal_integral))
     return primal_integral
+
+def load_solution_appsi(opt, config):
```
Comment (bernalde) [inline pyomo/contrib/mindtpy/util.py:949]: This won't be neccesary once the APPSI issues are addressed, right?

File: pyomo/contrib/mindtpy/util.py [hunk 8]
```diff
@@ -499,6 +502,16 @@ def set_solver_options(opt, solve_data, config, solver_type, regularization=Fals
...
+        # opt.options['load_solution'] = False
+        if regularization is True:
+            if config.solution_limit is not None:
+                opt.options['mip_limits_solutions'] = config.solution_limit
+            opt.options['mip_strategy_presolvenode'] = 3
+            if config.add_regularization in {'hess_lag', 'hess_only_lag'}:
+                opt.options['optimalitytarget'] = 3
     elif solver_name == 'glpk':
         opt.options['tmlim'] = remaining
         # TODO: mipgap does not work for glpk yet
```
Comment (bernalde) [inline pyomo/contrib/mindtpy/util.py:517]: Maybe we should create an issue mentioning this, as it is an important feature of a MIP solver and many people use GLPK with Pyomo (at least as an starting solver)

**Review by bernalde — CHANGES_REQUESTED** [review]
Good PR Zedong, this is also a good way of battle-testing APPSI (I think several issues have raised from trying to get this implementation working). Shall we wait for those issues to be resolved before merging this PR? We should at least mention in the code which issues #'s are related to certain lines of code to remove them after the issues are resolved.

File: pyomo/contrib/mindtpy/util.py (hunk 6 above)
Comment (ZedongPeng) [reply pyomo/contrib/mindtpy/util.py:508]: It's redundant. I'll remove it.

File: pyomo/contrib/mindtpy/util.py (hunk 7 above)
Comment (michaelbynum) [reply pyomo/contrib/mindtpy/util.py:948]: I would recommend something like the following here:

```
def load_solution_appsi(results: appsi.base.Results, config):
    assert isinstance(config.mip_solver, appsi.base.Solver)
    if results.best_feasible_objective is not None:
        results.solution_loader.load_vars()
```

Then there is no need to distinguish between specific solvers and no need to access private attributes.

Comment (ZedongPeng) [reply pyomo/contrib/mindtpy/util.py:948]: Great. Thanks.

Comment (michaelbynum) [reply pyomo/contrib/mindtpy/util.py:948]: Oh, ignore that. This is using the wrapper to make the solver look like a standard solver. Instead, you should be able to do the following:

```
def load_solution_appsi(model, results):
    if pyo.check_optimal_termination(results):
        model.solutions.load_from(results)
```

File: pyomo/contrib/mindtpy/util.py [hunk 9]
```diff
@@ -499,6 +502,16 @@ def set_solver_options(opt, solve_data, config, solver_type, regularization=Fals
             opt._solver_model.parameters.mip.strategy.presolvenode.set(3)
             if config.add_regularization in {'hess_lag', 'hess_only_lag'}:
                 opt._solver_model.parameters.optimalitytarget.set(3)
+    elif solver_name == 'appsi_cplex':
+        opt.options['timelimit'] = remaining
+        opt.options['mip_tolerances_mipgap'] = config.mip_solver_mipgap
```
Comment (michaelbynum) [inline pyomo/contrib/mindtpy/util.py:507]: Here you should be able to do something like:

```
elif isinstance(opt, appsi.base.Solver):
    opt.config.time_limit = remaining
    opt.config.mip_gap = config.mip_solver_mipgap
```

which is not solver specific. It may not matter since it looks like you need other solver specific options.

File: pyomo/contrib/mindtpy/util.py [hunk 10]
```diff
@@ -79,7 +79,10 @@ def model_is_valid(solve_data, config):
             set_solver_options(mainopt, solve_data,
                                config, solver_type='mip')
             mainopt.solve(solve_data.original_model,
-                          tee=config.mip_solver_tee, **config.mip_solver_args)
+                          tee=config.mip_solver_tee,
+                          load_solutions=config.mip_solver not in {'appsi_cplex', 'appsi_gurobi'},
+                          **config.mip_solver_args)
+            load_solution_appsi(mainopt, config)
```
Comment (michaelbynum) [inline pyomo/contrib/mindtpy/util.py:85]: Instead of what I mentioned below, you could do

```
results = main opt.solve(
    solve_data.original_model,
    tee=config.mip_solver_tee,
    load_solutions=False,
    **config.mip_solver_args
)
if pyo.check_optimal_termination(results):
    solve_data.original_model.solutions.load_from(results)
```

Then, you would not need the `load_solution_appsi` function.

Comment (michaelbynum) [reply pyomo/contrib/mindtpy/util.py:85]: If you want to load the solution with termination conditions other than optimal, you can do that as well:

```
results = main opt.solve(
    solve_data.original_model,
    tee=config.mip_solver_tee,
    load_solutions=False,
    **config.mip_solver_args
)
if len(results.solution > 0):
    solve_data.original_model.solutions.load_from(results)
```

File: pyomo/contrib/mindtpy/config_options.py [hunk 11]
```diff
@@ -575,4 +575,23 @@ def check_config(config):
...
+                            "mip_solver will be changed to Cplex")
+            config.mip_regularization_solver = 'cplex'
+        if config.mip_regularization_solver == 'appsi_gurobi':
+            config.logger.info("APPSI-GUROBI cannot get duals for mixed-integer problems"
+                            "mip_solver will be changed to GUROBI")
+            config.mip_regularization_solver = 'gurobi'
+        if config.mip_regularization_solver == 'appsi_gurobi':
+            config.logger.info("APPSI-GUROBI cannot get duals for mixed-integer problems"
+                            "mip_solver will be changed to GUROBI")
+            config.mip_regularization_solver = 'gurobi'
```
Comment (michaelbynum) [inline pyomo/contrib/mindtpy/config_options.py:597]: Does this work? I did not think Gurobi provided duals for mixed-integer problems regardless of the Pyomo interface.

File: .github/workflows/test_branches.yml [hunk 12]
```diff
@@ -259,6 +259,13 @@ jobs:
         # Note: some pypi packages are not available through conda
         PYOMO_DEPENDENCIES=`python setup.py dependencies \
             --extras "$EXTRAS" | tail -1`
+        # HACK: Remove problem packages on conda+Linux
+        if test "${{matrix.TARGET}}" == linux; then
+            WORDSTOREMOVE="casadi numdifftools pint"
+            for WORD in $WORDSTOREMOVE; do
+                PYOMO_DEPENDENCIES=${PYOMO_DEPENDENCIES//$WORD/}
+            done
+        fi
```
Comment (michaelbynum) [inline .github/workflows/test_branches.yml:268]: Are the changes to GitHub Actions still necessary? Do you need to merge main into this branch?

**Review by michaelbynum — CHANGES_REQUESTED** [review]
My only real concern is the changes to the GHA workflows. The rest of my comments are just informational.

File: .github/workflows/test_branches.yml (hunk 12 above)
Comment (ZedongPeng) [reply .github/workflows/test_branches.yml]: Sorry. I forgot to merge main into this branch. Fixed.

File: pyomo/contrib/mindtpy/config_options.py (hunk 11 above)
Comment (ZedongPeng) [reply pyomo/contrib/mindtpy/config_options.py:597]: You are right. Fixed.

File: pyomo/contrib/mindtpy/config_options.py (hunk 3 above)
Comment (ZedongPeng) [reply pyomo/contrib/mindtpy/config_options.py:580]: Any suggestion for the name?

File: pyomo/contrib/mindtpy/util.py (hunk 8 above)
Comment (ZedongPeng) [reply pyomo/contrib/mindtpy/util.py]: This comment is outdated. MIPGAP is already supported by GLPK with Pyomo. Fixed.

File: pyomo/contrib/mindtpy/config_options.py (hunk 3 above)
Comment (bernalde) [reply pyomo/contrib/mindtpy/config_options.py:580]: `compute_dual_at_solution` or `calculate_dual_at_solution`

**Comment by ZedongPeng** [comment]
Hi @michaelbynum .
Now the tests will fail due to appsi_solver not available error.
Do you have any suggestions to fix it? Many thanks.
```
_________ ERROR collecting pyomo/contrib/mindtpy/tests/test_mindtpy.py _________
pyomo/contrib/mindtpy/tests/test_mindtpy.py:68: in <module>
    class TestMindtPy(unittest.TestCase):
pyomo/contrib/mindtpy/tests/test_mindtpy.py:227: in TestMindtPy
    @unittest.skipUnless(SolverFactory('appsi_ipopt').available(),
pyomo/contrib/appsi/base.py:1306: in available
    raise ApplicationError(f'Solver {self.__class__} is not available ({ans}).')
E   pyomo.common.errors.ApplicationError: Solver <class 'pyomo.contrib.appsi.base.SolverFactoryClass.register.<locals>.decorator.<locals>.LegacySolver'> is not available (NotFound).
```

**Comment by ZedongPeng** [comment]
The tests all fail due to the same error.
```
self = <pyomo.common.dependencies.ModuleUnavailable object at 0x7fbe6eb668f0>
attr = '_dill'

    def __getattr__(self, attr):
        if attr in ModuleUnavailable._getattr_raises_attributeerror:
            raise AttributeError("'%s' object has no attribute '%s'"
                                 % (type(self).__name__, attr))
>       raise DeferredImportError(self._moduleunavailable_message())
E       pyomo.common.dependencies.DeferredImportError: The pympler module (an optional Pyomo dependency) failed to import: ModuleNotFoundError: No module named 'pympler'

pyomo/common/dependencies.py:69: DeferredImportError
```

**Comment by blnicho** [comment]
> The tests all fail due to the same error.
> 
> ```
> self = <pyomo.common.dependencies.ModuleUnavailable object at 0x7fbe6eb668f0>
> attr = '_dill'
> 
>     def __getattr__(self, attr):
>         if attr in ModuleUnavailable._getattr_raises_attributeerror:
>             raise AttributeError("'%s' object has no attribute '%s'"
>                                  % (type(self).__name__, attr))
> >       raise DeferredImportError(self._moduleunavailable_message())
> E       pyomo.common.dependencies.DeferredImportError: The pympler module (an optional Pyomo dependency) failed to import: ModuleNotFoundError: No module named 'pympler'
> 
> pyomo/common/dependencies.py:69: DeferredImportError
> ```

This test failure is not unique to this PR and is being tracked in #2414

File: pyomo/contrib/mindtpy/mip_solve.py [hunk 13]
```diff
@@ -85,15 +89,15 @@ def solve_main(solve_data, config, fp=False, regularization_problem=False):
...
-                                                                   solve_data.mip.MindtPy_utils.loa_proj_mip_obj),
+                                                               value(solve_data.mip.MindtPy_utils.loa_proj_mip_obj),
                                                                solve_data.primal_bound, solve_data.dual_bound, solve_data.rel_gap,
                                                                get_main_elapsed_time(solve_data.timing)))
 
     elif main_mip_results.solver.termination_condition is tc.infeasibleOrUnbounded:
         # Linear solvers will sometimes tell me that it's infeasible or
         # unbounded during presolve, but fails to distinguish. We need to
         # resolve with a solver option flag on.
+        # TODO: appsi_cplex will fail here. Need to be fixed. test_mindtpy_feas_pump.py  test_mindtpy_global.py
```
Comment (bernalde) [inline pyomo/contrib/mindtpy/mip_solve.py:100]: We should add this to an issue such that we keep track of it, and then reference the issue here in case we want to merge this PR before it is fixed

File: pyomo/contrib/mindtpy/tests/unit_test.py [hunk 14]
```diff
@@ -331,17 +331,6 @@ def test_handle_termination_condition(self):
             check_config(config)
             self.assertEqual(config.regularization_mip_threads, 8)
 
-            config.mip_solver = 'cplex'
```
Comment (bernalde) [inline pyomo/contrib/mindtpy/tests/unit_test.py:334]: Why did we remove some of the unit tests?

**Review by bernalde — CHANGES_REQUESTED** [review]
I'm requesting two small changes, basically referencing an issue on APPSI CPLEX that was identified in case we are merging this before the fix, or waiting until it is fixed to remove the comment. Michael also left a good recommendation regarding solver options which might remove some of the boilerplate we have to set subsolver options.

File: pyomo/contrib/mindtpy/mip_solve.py (hunk 13 above)
Comment (ZedongPeng) [reply pyomo/contrib/mindtpy/mip_solve.py]: Fixed

**Review by bernalde — APPROVED** [review]

**Review by michaelbynum — APPROVED** [review]

**Comment by bernalde** [comment]
I would wait for #2432 to be merged before this one gets inspected and tested on Jenkins

**Comment by bernalde** [comment]
With #2432 merged into this PR and all tests passing (except one independent from this PR) I think it is ready for inspection and testing on Jenkins.
