### ISSUE TITLE
Best practice for subclassing AbstractModel

### ISSUE THREAD

**Issue by jackjackk** [Pyomo/pyomo#270]
I would like to create a subclass of AbstractModel.
Let say I would like to use a "self-contained" QuadModel which is able to solve itself, and which I might want to subclass in turn e.g. changing only the objective_rule.
```
from pyomo.environ import *
from pyomo.opt import SolverManagerFactory, SolverFactory

class QuadModel(AbstractModel):

    @staticmethod
    def objective_rule(model):
        return (model.x - 3) * (model.x - 3)

    def __init__(self):
        # Model
        super().__init__()
        self.x = Var(bounds=(-10,10), within=Reals)
        self.objective = Objective(rule=self.__class__.objective_rule, sense=minimize)

        # Aux
        self.inst = None
        self.res = None
        self._solman = SolverManagerFactory('serial')
        self._opt = SolverFactory('ipopt')

    def solve(self):
        self.inst = self.create_instance()
        self.res = self._solman.solve(self.inst, opt=self._opt, tee=True, timelimit=None)
        return self.inst

# Solve
qm = QuadModel()
qm.solve()
print(qm.res)
qm.inst.x.pprint()
```
While the code above works, I get a warning:
```
WARNING: Reassigning the non-component attribute inst
	on block (model).unknown with a new Component
	with type <class 'pyomo.core.base.PyomoModel.ConcreteModel'>.
	This is usually indicative of a modelling error.
	To avoid this warning, explicitly delete the attribute:
	    del unknown.inst
```
I don't know the entirety of pyomo internals, but it seems that AbstractModel is taking full control of setattr, and so I'm a bit concerned that what I do with my subclass outside Pyomo strict modelling could interfere with these internals. Is this really the case?

An alternative I can think of (changes highlighted in comments):
```
from pyomo.environ import *
from pyomo.opt import SolverManagerFactory, SolverFactory

# INHERIT FROM OBJECT
class QuadModel(object):

    # ADDED

    CLASS_ATTRS = ['inst', 'res']

    def __getattr__(self, item):
        return getattr(self._model, item)

    def __setattr__(self, key, value):
        if (key[0] == '_') or (key in self.__class__.CLASS_ATTRS):
            return super().__setattr__(key, value)
        return setattr(self._model, key, value)

    # LIKE BEFORE, WITH THE ADDITION OF A _MODEL ATTRIBUTE

    @staticmethod
    def objective_rule(model):
        return (model.x - 3) * (model.x - 3)

    def __init__(self):
        super().__init__()
        # Model
        self._model = AbstractModel()
        self.x = Var(bounds=(-10, 10), within=Reals)
        self.objective = Objective(rule=self.__class__.objective_rule, sense=minimize)

        # Aux
        self.inst = None
        self.res = None
        self._solman = SolverManagerFactory('serial')
        self._opt = SolverFactory('ipopt')


    def solve(self):
        self.inst = self.create_instance()
        self.res = self._solman.solve(self.inst, opt=self._opt, tee=True, timelimit=None)
        return self.inst

# Solve
qm = QuadModel()
qm.solve()
print(qm.res)
qm.inst.x.pprint()
```
where I propagate get/set attr to an inner AbstractModel `_model`, and differentiate between attributes of the wrapper class (identified by a leading `_` or belonging to the `CLASS_ATTRS` list) and all the others for `_model`.

Although the latter approach gives me no warnings, could also this interfere with Pyomo internals? In general what would be the preferred way to go?

Thanks

**Comment by jackjackk** [comment]
A more specific problem I'm having regards functions addition to AbstractModel subclasses. For example, if I want to define my own power function in the first example above, changing QuadModel with:
```
    @staticmethod
    def objective_rule(model):
        return model.mypower(model.x - 3, 2)

    def mypower(self, x, n):
        if isinstance(n, int) and (n<5):
            ret = x
            for _ in range(n-1):
                ret *= x
        else:
            ret = pow(x, n)
        return ret
```
this, if I'm not mistaken, used to work with Pyomo 5.2, but with Pyomo 5.3 I get this error:
```
ERROR: Rule failed when generating expression for objective objective:
	AttributeError: 'ConcreteModel' object has no attribute 'mypower'
ERROR: Constructing component 'objective' from data=None failed:
	AttributeError: 'ConcreteModel' object has no attribute 'mypower'
```

**Comment by blnicho** [comment]
@jackjackk in general it is easier to use a containment design pattern instead of subclassing from Pyomo objects directly. You can see an example of how this was done for another project here: https://github.com/sandialabs/chama/blob/master/chama/optimize.py

Why are you using AbstractModel instead of ConcreteModel?

**Comment by jackjackk** [comment]
@blnicho thanks for the reply, I'll check your example!

I'm using AbstractModel because I like the idea of using a dictionary for all the data and of delaying the construction of the model until all data is given (e.g. think of a number of time steps which gives the cardinality of the set of time steps for example). would you recommend against AbstractModel?

also, to me, the containment model seems more for "use and dispose" setups, losing a bit of the clarity of class inheritance for managing similar models sharing component definitions. do you think it is appropriate also for this use case?

**Comment by whart222** [comment]
This is not the right forum for questions.
