### PR TITLE
Fixing NEOS interface when behind a proxy in Python3.x

### LINKED ISSUE #560: NEOS server does not work on proxy connections
Reiterating an issue that came up in #551 with the NEOS server. The `pyomo help -s` command still does not work when called within a proxy network, due to an issue with the neos server. The issue is in the `pyomo.neos.kestrel` module with handling proxy connections. We implement a custom [ProxiedTransport](https://github.com/Pyomo/pyomo/blob/bb84f26c051f20caf639839bb1cec0188276335a/pyomo/neos/kestrel.py#L50) class that is used when proxy related environment variables are set, which it seems was copied from an online source. However, this class no longer functions properly. The first issue is a discrepancy in number of arguments, but there are deeper issues in the class that are not compatible with the rest of the `xmlrpclib` module. [Here](https://gist.github.com/nathforge/980961) might be a potential solution from quick googling.

When calling `pyomo help -s`, this is the traceback:

```
Traceback (most recent call last):
  File "/ascldap/users/gseastr/envs/python3.6/bin/pyomo", line 11, in <module>
    load_entry_point('Pyomo', 'console_scripts', 'pyomo')()
  File "/home/gseastr/envs/pyomo/pyomo/scripting/pyomo_main.py", line 82, in main
    retval = _options.func(_options)
  File "/home/gseastr/envs/pyomo/pyomo/scripting/driver_help.py", line 456, in help_exec
    help_solvers()
  File "/home/gseastr/envs/pyomo/pyomo/scripting/driver_help.py", line 373, in help_solvers
    kestrel = pyomo.neos.kestrel.kestrelAMPL()
  File "/home/gseastr/envs/pyomo/pyomo/neos/kestrel.py", line 66, in __init__
    self.setup_connection()
  File "/home/gseastr/envs/pyomo/pyomo/neos/kestrel.py", line 87, in setup_connection
    result = self.neos.ping()
  File "/home/gseastr/envs/python3.6/lib/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/home/gseastr/envs/python3.6/lib/python3.6/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/home/gseastr/envs/python3.6/lib/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/home/gseastr/envs/python3.6/lib/python3.6/xmlrpc/client.py", line 1166, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
TypeError: send_request() takes 4 positional arguments but 5 were given
```

### PR DESCRIPTION
**Pull request by jsiirola**
## Summary/Motivation:
This reworks the NEOS proxy interface so that it works when the client is behind a proxy server in Python 3.x (it previously only worked in Python 2.x).  

## Changes proposed in this PR:
- Rework how ProxiedTransport objects are defined.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by gseastream** [comment]
Running this locally, this only seems to work on Python 2.7 but not Python 3 or higher. Running `pyomo help -s` in python 2, I get at the bottom:

```
NEOS Solver Interfaces
----------------------
The neos solver manager supports solver interfaces that can be
executed remotely on the NEOS optimization server.  The following
solver interfaces are available with your current system
configuration:

    bonmin       Heuristic MINLP solver
    cbc          MILP solver
    conopt       Feasible path NLP solver
    couenne      Exact MINLP solver
    cplex        MILP solver
    filmint      Heuristic MINLP solver
    filter       SQP NLP solver
    ipopt        Interior point NLP solver
    knitro       Convex MINLP solver
    l-bfgs-b     Bound-constrained NLP solver
    lancelot     Augmented Lagrangian NLP solver
    loqo         Interior point NLP solver
    minlp        Heuristic MINLP solver
    minos        SLC NLP solver
    minto        MILP solver
    mosek        Interior point NLP solver
    ooqp         Convex QP solver
    path         Nonlinear MCP solver
    snopt        SQP NLP solver
```

But in python 3+ I get:

```
NEOS Solver Interfaces
----------------------
The neos solver manager supports solver interfaces that can be
executed remotely on the NEOS optimization server.  This server is not
available with your current system configuration.
```

**Comment by jsiirola** [comment]
That is odd, as it appears to work for both 2.x and 3.x for me, tested on both THEL6 and RHEL7 boxes.  Can you try running again?  I have seen the proxy server time out somewhat regularly lately - that can confuse Pyomo into thinking that NEOS is not available.

**Comment by gseastream** [comment]
I just ran it 5 times in a row and I got the same result. It doesn't appear to be a timeout issue since the result is immediate. I wonder what the issue may be and how significant it is if it works for you.

**Comment by gseastream** [comment]
I just reinstalled python3.6, pyomo, and pyutilib in a virtual environment and got the same behavior.

**Comment by jsiirola** [comment]
@gseastream: are you also working in a VM?  I can confirm that this works on 3.5 and 3.6 with bare metal machines.  @blnicho: can you try on a non-VM?

**Comment by gseastream** [comment]
I always work in conda environments set to different versions of python.

**Comment by blnicho** [comment]
I just tried on sisu and I'm getting the following error for both 2.7 and 3.5:

```
Traceback (most recent call last):
  File "/ascldap/users/blnicho/local/python/pyomo/bin/pyomo", line 11, in <module>
    load_entry_point('Pyomo', 'console_scripts', 'pyomo')()
  File "/home/blnicho/Research/pyomo/pyomo/scripting/pyomo_main.py", line 82, in main
    retval = _options.func(_options)
  File "/home/blnicho/Research/pyomo/pyomo/scripting/driver_help.py", line 456, in help_exec
    help_solvers()
  File "/home/blnicho/Research/pyomo/pyomo/scripting/driver_help.py", line 373, in help_solvers
    kestrel = pyomo.neos.kestrel.kestrelAMPL()
  File "/home/blnicho/Research/pyomo/pyomo/neos/kestrel.py", line 107, in __init__
    self.setup_connection()
  File "/home/blnicho/Research/pyomo/pyomo/neos/kestrel.py", line 131, in setup_connection
    result = self.neos.ping()
  File "/projects/sems/install/rhel7-x86_64/pyomo/compiler/python/2.7.15/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/projects/sems/install/rhel7-x86_64/pyomo/compiler/python/2.7.15/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/projects/sems/install/rhel7-x86_64/pyomo/compiler/python/2.7.15/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/projects/sems/install/rhel7-x86_64/pyomo/compiler/python/2.7.15/lib/python2.7/xmlrpclib.py", line 1303, in single_request
    h = self.make_connection(host)
  File "/home/blnicho/Research/pyomo/pyomo/neos/kestrel.py", line 63, in make_connection
    return connClass(self.proxy.hostname, self.proxy.port)
  File "/projects/sems/install/rhel7-x86_64/pyomo/compiler/python/2.7.15/lib/python2.7/httplib.py", line 736, in __init__
    (self.host, self.port) = self._get_hostport(host, port)
  File "/projects/sems/install/rhel7-x86_64/pyomo/compiler/python/2.7.15/lib/python2.7/httplib.py", line 768, in _get_hostport
    i = host.rfind(':')
AttributeError: 'NoneType' object has no attribute 'rfind'
```

**Comment by jsiirola** [comment]
This appears to be a problem with anaconda.  I can confirm that the proxy connection doesn't appear to work through miniconda on the same machine where native builds of Python work fine (and with the same system environment).

That said, in my opinion, the problem with Anaconda should be dealt with in a separate issue, as this PR resolves the exception in master, and does work for bare metal builds.

**Comment by jsiirola** [comment]
@blnicho: your error appears to be because of a malformed proxy URL.  Does your `http_proxy` / `https_proxy` not begin with `http://`?  28900e adds a trap for this, and should avoid the exception.

**Comment by gseastream** [comment]
I can confirm it works on python 3.7 installed from source on my machine.

**Comment by blnicho** [comment]
@jsiirola oops, my mistake. I fixed the proxy settings and now the fix works for me on sisu for both 2.7 and 3.5.

**Comment by jsiirola** [comment]
The coverage tests of this PR are low because the Travis/Appveyor tests are not behind a proxy server (the code is tested when tests are run behind a proxy), and should not hold up merging the PR.
